### ISSUE TITLE
Which is your favourite? And why

### ISSUE THREAD

**Issue by jakearchibald** [csswizardry/ama#11]

**Comment by nickdunn** [comment]
Seconded.

**Comment by csswizardry** [comment]
Well I think the first thing we need to do is define _favourite_. Is is an objective look at the better option given all available information, or is it more of a question of opinion—are there strong emotional or subjective reasons for my preference of one over the other?

Once we have an understanding of the metrics by which we’re measuring _favourite_, I would hopefully be able to draw some form of reliable conclusion, though that is not to say that my decision will remain as it is forever: I may change my mind based on the availability of new information, or other options may begin to make themselves apparent.

Regardless, you’re my favourite, for hopefully obvious reasons 😘
