### ISSUE TITLE
CSS vs Front End Performance. At the moment, which do you find the most exciting?

### ISSUE THREAD

**Issue by BenjaminRCooper** [csswizardry/ama#16]
and why.

**Comment by csswizardry** [comment]
Hmmmm. Honestly, right now, I’m finding performance more interesting from a personal point of view.

I’ve been providing CSS architecture consultancy for over 3 years now, so it’s something I am very familiar with. I still find it fascinating, and very enjoyable (every client has different problems to bring to the table), but for me performance is a new avenue to explore.

I’ll continue to provide CSS knowledge for clients, and I’ve already been doing performance work to some degree for about 5 years, but I’m slowing introducing more of the latter as well as the CSS work.

What I do really like is the crossover that the two share—_that’s_ interesting 😀

**Comment by BenjaminRCooper** [comment]
[I knew it](http://i.imgur.com/UxaiFwK.gif)
