### ISSUE TITLE
Can I work for you?

### ISSUE THREAD

**Issue by EzeRangel** [csswizardry/ama#25]
This is the day that I leave my job and then I found this.

Well if I can ask anything, can I work with you?

You have been my mentor without know it. I don't really looking for money or anything like that I just want to learn (and give) more from the person I admire.

**Comment by csswizardry** [comment]
Hey!

Well, firstly congratulations on leaving your job! A scary but exciting time, I’m sure!

> …can I work with you?

I wish I could just say **yes!** But unfortunately I just don’t have the time, consistency, or predictability to have anyone relying on me.

That said, drop me an email letting me know what kind of experience you have, what kind of things you’re looking for, and just to say hi, and I’ll see if anything appropriate ever comes up.

Plus you can always reach out to me at any time with questions about careers or tech—I always try to answer every email I receive.

Best of luck!
