### ISSUE TITLE
How do you choose which conferences to speak at?

### ISSUE THREAD

**Issue by SaraSoueidan** [csswizardry/ama#35]
You decline some speaking engagements every now and then? How do you choose which ones you accept? Given that you can travel practically anywhere, do you have any specific criteria as to why you wouldn’t travel to speak somewhere?

**Comment by csswizardry** [comment]
I like this question!

I’m super eager and enthusiastic and excitable, so I say yes to most (if not all) conference requests—if someone is willing to fly me out somewhere in return for ~45 minutes of my time on stage I would be foolish to say no!

I’m lucky in that I have relatively immediate access to most countries, and a schedule that allows for for me to hop around a lot. This means I don’t even really need much notice/lead time to speak at events.

However, there are some conferences that I decline:

* **For-profit events that don’t pay speakers:** It’s not cool to make money off of somebody else’s free labour.
* **Any event that doesn’t pay expenses:** Expecting someone to pay to come and speak at your event is frankly just bizarre. Non-profit or not, you should’t be asking people to make their own way to deliver content for you.
* **Events where I don’t feel qualified:** I don’t normally feel comfortable speaking at JS/back-end/design events unless the organisers are completely aware of the kind of content I will be delivering.
* **Events that don’t offer enough travel nights:** I’m absolutely not a diva in the slightest (I travel economy and stay in the cheapest hotels I can find) but so many conferences have asked me to take super long haul flights (we’re talking ~24hr) for only two nights’ accommodation. No one should be expected to travel half way around the world for two nights—you can’t function properly like that. It’s a shame, but they’re usually an immediate no.

I don’t have any super strict requirements or feelings regarding CFPs—I don’t mind if your conference is 100% curated or is 100% applied for—but if you invite me to speak and then make me submit an application, I’m probably going to say no on principle. It feels pretty disrespectful, like: _‘Hey! I’d love if you came to my wedding!’_ ‘Wow, absolutely, I’d be delighted!’ _‘Okay, cool, but first you need to fill out this application and convince us why you should be there.’_

But honestly, for the most part, if you’ll cover my expenses I’ll probably come and speak. It’s so much fun getting to hang out with new people. I’m so incredibly lucky.
