### ISSUE TITLE
What future CSS features are you most excited about?

### ISSUE THREAD

**Issue by danielpost** [csswizardry/ama#4]

**Comment by csswizardry** [comment]
I guess the features themselves aren’t future features, but pretty new stuff that isn’t at critical mass yet:

* **Grid:** Yes. Absolutely. This is gonna be so cool!
* **Custom Properties:** (AKA CSS Variables): These are going to be so useful for so many things that were previously pretty cumbersome. [Theming](https://csswizardry.com/2016/10/pragmatic-practical-progressive-theming-with-custom-properties/) springs to mind.
* **`@supports`:** Again, usable right now, but still off of so many peoples’ radars. Native feature detection is so nice; I make use of it quite a lot, but I wish more people did.
* **`all: initial;`:** This this is just gold. I mean, this is _so good_. Can’t wait until it’s usable everywhere.

So yeah, nothing around the corner is exciting me too much (I haven’t really been looking, unfortunately), but there are some things already (partially) available that I cannot wait to become ubiquitous.

**Comment by danielpost** [comment]
Awesome, thanks! Have you ever tried [cssnext](http://cssnext.io/features/)?
