### ISSUE TITLE
Any hints and tips working on a large sites with Adverts (and javascript in general)

### ISSUE THREAD

**Issue by matt-harris** [csswizardry/ama#41]
Hey Harry,

Was wondering if/how you have dealt with the performance of Adverts on large sites you have worked on?

Also, any tips on how you profile a sites scripts to find (if any) are blocking rendering.

cheers

**Comment by csswizardry** [comment]
Hey!

Sorry I missed this and took over two years to respond…

* Always make sure ads (and all third parties, really) are loaded asynchronously where possible.
* `preconnect` any key third party origins.
* See my entire talk about this stuff! [_It’s My (Third) Party, and I’ll Cry if I Want To_](https://speakerdeck.com/csswizardry/its-my-third-party-and-ill-cry-if-i-want-to)
