### ISSUE TITLE
How do you organize your work ?

### ISSUE THREAD

**Issue by ayadcodes** [csswizardry/ama#43]
Hey Harry, first thank you for doing this...

My question is about something not a lot of devs talk about; in my opinon; your folder organization.

How do you organize your folders ? do you store clients' documents and media in the same folder of the project ? or do you use another method ?

How much do you backup your data ? what do you use for that ? and do you backup multiple folders or you have one root folder(i.e Sites) ?

**Comment by csswizardry** [comment]
Hey!

This is an interesting one. I’m honestly not as organised as I should be, and there’s probably a lot of duplication and waste in my process, but generally I will have two locations for client work.

Firstly, for non-code assets like contracts, documents, etc., I have a `Clients/` directoy in my Dropbox:

* `Clients/`
  * `<Client>/`
    * `<Year>/`
      * `Assets/`
      * `Contracts/`
      * `Documents/`
      *  `Invoicing/`


Secondly, there’s code stuff, and that’s usually a lot more simple:

* `~/Sites/`
  * `clients/`
    * `<client>/`

Everything is in the cloud and I have a 4TB Western Digital drive for anything critical or that can’t be recovered from cloud backups.
