### ISSUE TITLE
According to you, what are some best ways to get good at CSS? 

### ISSUE THREAD

**Issue by ankurkaushal** [csswizardry/ama#52]
Any recommendations for books, sites (I regularly refer to CSS Tricks :D) or materials would be helpful :)

**Comment by csswizardry** [comment]
* **Pick things apart, reverse engineer things, have fun, experiment.** A good way to learn CSS is to see how other things have been done, and maybe even trying to improve on it.
* **Know what different aspects of CSS there are.** There are individual specifications to be aware of that will hugely improve the quality of your code (Grid, Flexbox, etc.), and there’s also the fairly immutable facets of architecture (selectors, organisation, grouping, etc.) and performance (critical CSS, CSS loading strategies, rendering performance, etc.).
* **Understand that clever ≠ good.** Optimising for terseness or trickery might feel kinda fun and cool, but a hallmark of good CSS is its ability to be understood by many people over time.
* **Know who to follow.** CSS Tricks is a great start! But also look up work by Nicolas Gallagher, Jonathan Snook, Rachel Andrew, Lea Verou, Ana Tudor, Nicole Sullivan, and Jen Simmons.

I hope that helps!
