### ISSUE TITLE
What do you think about CSS Grid and when will you use it?

### ISSUE THREAD

**Issue by ror-y** [csswizardry/ama#8]

**Comment by csswizardry** [comment]
I think it’s amazing! It’s gonna be great for more traditional publication style layouts.

> …when will you use it?

Once I full understand it (Rachel Andrew is doing some killer work here[1]), and when the need arises. As with all tools, I wait until I need them before I use them. I’m working with a large newspaper publisher at the moment and it might be of use to them at some point.

1. http://gridbyexample.com/
