### ISSUE TITLE
What's your favourite colour format?

### ISSUE THREAD

**Issue by jonrandahl** [csswizardry/ama#9]
- [ ] Named
- [ ] Hex
- [ ] RGB
- [x] HSL

Bonus:
- [ ] Alpha Based

**Comment by csswizardry** [comment]
Oh man, difficult! I was thinking about this today actually—despite using Hex, I reckon HSL is probably the most elegant. Then Hex, then RGB, then named. Alpha where necessary.

**Comment by jonrandahl** [comment]
Cheers Harry, I was wondering as I've recently migrated to HSL from RBG. It's been a long time since I've written Hex or Named ... :-D
